<!-- FAQs Section -->
<section id="faqs" class="py-20 bg-gray-50">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16">
      <h2 class="text-4xl font-bold text-gray-900 mb-4">
        Got Questions? We've Got Answers.
      </h2>
    </div>

    <div class="space-y-6">
      <div class="bg-white rounded-2xl shadow-lg p-8">
        <h3 class="text-xl font-semibold text-gray-900 mb-4">
          How does RizzGPT work?
        </h3>
        <p class="text-gray-600">
          RizzGPT leverages state-of-the-art AI to analyze screenshots of dating
          profiles or conversations. It understands context, tone, and visual
          cues, then generates witty, engaging, and personalized responses
          designed to spark connection and get replies.
        </p>
      </div>

      <div class="bg-white rounded-2xl shadow-lg p-8">
        <h3 class="text-xl font-semibold text-gray-900 mb-4">
          What kind of results can I expect with RizzGPT?
        </h3>
        <p class="text-gray-600">
          Our users consistently report a significant increase in matches, more
          engaging conversations, and ultimately, more successful dates. We've
          seen replies generated by RizzGPT get 2X the response rate compared to
          average messages.
        </p>
      </div>

      <div class="bg-white rounded-2xl shadow-lg p-8">
        <h3 class="text-xl font-semibold text-gray-900 mb-4">
          Can I use RizzGPT for any dating app or platform?
        </h3>
        <p class="text-gray-600">
          Absolutely! RizzGPT's flexibility is its strength. Since it works by
          analyzing screenshots, it's compatible with virtually any dating app
          or chat platform that uses text and images. Your secret weapon,
          wherever you flirt.
        </p>
      </div>

      <div class="bg-white rounded-2xl shadow-lg p-8">
        <h3 class="text-xl font-semibold text-gray-900 mb-4">
          Is my data safe?
        </h3>
        <p class="text-gray-600">
          Your privacy is our top priority. We do not store, sell, or share your
          chat data. Screenshots are processed for message generation and then
          immediately discarded. Our systems are encrypted to ensure your
          information is secure.
        </p>
      </div>

      <div class="bg-white rounded-2xl shadow-lg p-8">
        <h3 class="text-xl font-semibold text-gray-900 mb-4">
          Will the recipient find out I'm using AI?
        </h3>
        <p class="text-gray-600">
          Not at all! RizzGPT is designed to generate natural, human-sounding
          responses that blend seamlessly into your conversations. The goal is
          to provide inspiration and unique angles, not robotic replies. Many
          users even adapt the suggestions to truly make them their own.
        </p>
      </div>

      <div class="bg-white rounded-2xl shadow-lg p-8">
        <h3 class="text-xl font-semibold text-gray-900 mb-4">
          Does it work on text or images?
        </h3>
        <p class="text-gray-600">
          RizzGPT excels with both! Our AI can read and understand text from
          bios and chat logs, but it also has image recognition capabilities to
          pick up on details in profile photos that can inspire a great opener.
        </p>
      </div>
    </div>
  </div>
</section>
