<script lang="ts">
  import * as Accordion from "$lib/ui/accordion";
</script>

<!-- FAQs Section -->
<section id="faqs" class="py-20">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16">
      <h2 class="text-4xl font-bold text-gray-900 mb-4">
        Got Questions? We've Got Answers.
      </h2>
    </div>

    <Accordion.Root
      type="multiple"
      class="bg-white rounded-2xl shadow-lg overflow-hidden"
    >
      <Accordion.Item value="how-it-works" class="border-gray-200">
        <Accordion.Trigger
          class="text-xl font-semibold text-gray-900 px-8 py-6 hover:bg-gray-50"
        >
          How does RizzGPT work?
        </Accordion.Trigger>
        <Accordion.Content class="px-8 pb-6 text-gray-600">
          RizzGPT leverages state-of-the-art AI to analyze screenshots of dating
          profiles or conversations. It understands context, tone, and visual
          cues, then generates witty, engaging, and personalized responses
          designed to spark connection and get replies.
        </Accordion.Content>
      </Accordion.Item>

      <Accordion.Item value="results" class="border-gray-200">
        <Accordion.Trigger
          class="text-xl font-semibold text-gray-900 px-8 py-6 hover:bg-gray-50"
        >
          What kind of results can I expect with RizzGPT?
        </Accordion.Trigger>
        <Accordion.Content class="px-8 pb-6 text-gray-600">
          Our users consistently report a significant increase in matches, more
          engaging conversations, and ultimately, more successful dates. We've
          seen replies generated by RizzGPT get 2X the response rate compared to
          average messages.
        </Accordion.Content>
      </Accordion.Item>

      <Accordion.Item value="compatibility" class="border-gray-200">
        <Accordion.Trigger
          class="text-xl font-semibold text-gray-900 px-8 py-6 hover:bg-gray-50"
        >
          Can I use RizzGPT for any dating app or platform?
        </Accordion.Trigger>
        <Accordion.Content class="px-8 pb-6 text-gray-600">
          Absolutely! RizzGPT's flexibility is its strength. Since it works by
          analyzing screenshots, it's compatible with virtually any dating app
          or chat platform that uses text and images. Your secret weapon,
          wherever you flirt.
        </Accordion.Content>
      </Accordion.Item>

      <Accordion.Item value="data-safety" class="border-gray-200">
        <Accordion.Trigger
          class="text-xl font-semibold text-gray-900 px-8 py-6 hover:bg-gray-50"
        >
          Is my data safe?
        </Accordion.Trigger>
        <Accordion.Content class="px-8 pb-6 text-gray-600">
          Your privacy is our top priority. We do not store, sell, or share your
          chat data. Screenshots are processed for message generation and then
          immediately discarded. Our systems are encrypted to ensure your
          information is secure.
        </Accordion.Content>
      </Accordion.Item>

      <Accordion.Item value="ai-detection" class="border-gray-200">
        <Accordion.Trigger
          class="text-xl font-semibold text-gray-900 px-8 py-6 hover:bg-gray-50"
        >
          Will the recipient find out I'm using AI?
        </Accordion.Trigger>
        <Accordion.Content class="px-8 pb-6 text-gray-600">
          Not at all! RizzGPT is designed to generate natural, human-sounding
          responses that blend seamlessly into your conversations. The goal is
          to provide inspiration and unique angles, not robotic replies. Many
          users even adapt the suggestions to truly make them their own.
        </Accordion.Content>
      </Accordion.Item>

      <Accordion.Item value="text-vs-images" class="border-gray-200 border-b-0">
        <Accordion.Trigger
          class="text-xl font-semibold text-gray-900 px-8 py-6 hover:bg-gray-50"
        >
          Does it work on text or images?
        </Accordion.Trigger>
        <Accordion.Content class="px-8 pb-6 text-gray-600">
          RizzGPT excels with both! Our AI can read and understand text from
          bios and chat logs, but it also has image recognition capabilities to
          pick up on details in profile photos that can inspire a great opener.
        </Accordion.Content>
      </Accordion.Item>
    </Accordion.Root>
  </div>
</section>
