<script lang="ts">
  import * as Accordion from "$lib/components/accordion";

  const faqItems = [
    {
      title: "How does RizzGPT work?",
      content: `
            RizzGPT leverages state-of-the-art AI to analyze screenshots of dating
            profiles or conversations. It understands context, tone, and visual
            cues, then generates witty, engaging, and personalized responses
            designed to spark connection and get replies.
            `,
    },
    {
      title: "What kind of results can I expect with RizzGPT?",
      content: `
            Our users consistently report a significant increase in matches,
            more engaging conversations, and ultimately, more successful dates.
            We've seen replies generated by RizzGPT get 2X the response rate
            compared to average messages.
            `,
    },
    {
      title: "Can I use RizzGPT for any dating app or platform?",
      content: `
            Absolutely! RizzGPT's flexibility is its strength. Since it works by
            analyzing screenshots, it's compatible with virtually any dating app
            or chat platform that uses text and images. Your secret weapon,
            wherever you flirt.
            `,
    },
    {
      title: "Does it work in any language?",
      content: `Yes!! You can upload a conversation / bio in any language, and our AI model will understand and give you the response in your native language`,
    },
    {
      title: "Is my data safe?",
      content: `
            Your privacy is our top priority. We do not store, sell, or share
            your chat data. Uploaded screenshots are end-to-end encrypted such that only you can
            see what you uploaded. Our systems are encrypted to ensure your information is secure.
            `,
    },
    {
      title: "Will the recipient find out I'm using AI?",
      content: `
            Not at all! RizzGPT is designed to generate natural, human-sounding
            responses that blend seamlessly into your conversations. The goal is
            to provide inspiration and unique angles, not robotic replies. Many
            users even adapt the suggestions to truly make them their own.
            `,
    },
    {
      title: "Does it work on images AND screen recordings?",
      content: `
            RizzGPT excels with both! Our AI can read and understand any text from
            a screen recordings and advanced recognition capabilities to help generate
            the best possible response for your partner.
            `,
    },
  ] as const;
</script>

<!-- FAQs Section -->
<section id="faqs" class="py-20">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16">
      <h2 class="text-4xl font-bold text-gray-900 mb-4">
        Got Questions? We've Got Answers.
      </h2>
    </div>

    <Accordion.Root
      type="multiple"
      class="bg-white rounded-2xl shadow-lg overflow-hidden"
    >
      {#each faqItems as item, index}
        <Accordion.Item
          value={String(index)}
          class={index === faqItems.length - 1
            ? "border-gray-200 border-b-0"
            : "border-gray-200"}
        >
          <Accordion.Trigger
            class="text-xl font-semibold text-gray-900 px-8 py-6 hover:bg-gray-50"
          >
            <span> {item.title} </span>
          </Accordion.Trigger>
          <Accordion.Content class="px-8 pb-6 text-gray-600">
            <div>{item.content.trim()}</div>
          </Accordion.Content>
        </Accordion.Item>
      {/each}
    </Accordion.Root>
  </div>
</section>
